#!/usr/bin/env bash
# ============================================================================
# ResiliaMap — scripts/gen-secrets.sh
# ----------------------------------------------------------------------------
# Write a populated .env.prod with fresh random secrets and assembled connection
# strings. You then edit DOMAIN, ACME_EMAIL and VITE_BASEMAP_STYLE_URL.
#
#   bash scripts/gen-secrets.sh            # refuses to clobber an existing file
#   FORCE=1 bash scripts/gen-secrets.sh    # overwrite
#
# License: AGPL-3.0-or-later. See DEPLOY.ResiliaMap.md.
# ============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=".env.prod"
if [[ -f "$OUT" && "${FORCE:-0}" != "1" ]]; then
  echo "Refusing to overwrite existing $OUT (set FORCE=1 to override)." >&2
  exit 1
fi

# URL-safe random secrets (alnum only — no '@', ':' or '/' to break the DSN).
# openssl|tr|cut avoids the `... | head -c N` SIGPIPE that aborts under pipefail
# (cut reads to EOF, so the producer never gets a closed pipe).
rand() {
  local n="${1:-32}"
  openssl rand -base64 "$(( n + 24 ))" | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-"$n"
}

PG_PW="$(rand 40)"
RO_PW="$(rand 40)"
HMAC="$(rand 48)"

cat > "$OUT" <<EOF
# Generated by scripts/gen-secrets.sh — DO NOT COMMIT. Fill DOMAIN/ACME_EMAIL/basemap.
POSTGRES_USER=resiliamap
POSTGRES_PASSWORD=${PG_PW}
POSTGRES_DB=resiliamap
POSTGRES_RO_PASSWORD=${RO_PW}

DATABASE_URL=postgres://resiliamap:${PG_PW}@db:5432/resiliamap
API_DATABASE_URL=postgres://resiliamap_ro:${RO_PW}@db:5432/resiliamap
TILESERV_DATABASE_URL=postgres://resiliamap_ro:${RO_PW}@db:5432/resiliamap

API_PORT=3801
CORS_ORIGIN=
WEBHOOK_SIGNING_SECRET=${HMAC}

# TODO: set a licensed basemap style (the public OSM CDN is not allowed in prod).
VITE_BASEMAP_STYLE_URL=

# TODO: your domain + Let's Encrypt contact.
DOMAIN=
ACME_EMAIL=
EOF

chmod 600 "$OUT"
echo "Wrote $OUT (mode 600)."
echo "NEXT: set DOMAIN, ACME_EMAIL, VITE_BASEMAP_STYLE_URL — and after first DB boot run:"
echo "  ALTER ROLE resiliamap_ro PASSWORD '${RO_PW}';   (see DEPLOY.ResiliaMap.md)"
